### PR TITLE
cleanup CHANGELOG

### PR DESCRIPTION
**Pull request by juwara0**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Updated** cleaned up CHANGELOG.md

### CODE REVIEW

**Comment by juwara0** [comment]
👍  self merging - I just cleaned up the CHANGELOG so we will have a fresh start.

**Comment by job13er** [comment]
👍

**Comment by job13er** [comment]
I don't think pull-approve picks up the 👍 if it's not the only thing in the comment 😞

**Comment by juwara0** [comment]
👍

**Pull request merged**
